# Lecture 5

## Existence of QR decomposition

### Lemma (Gram-Schmidt Process)
Let $\{a_1, \cdots, a_r\}$ are linear independent. Thus, $\exists \{q_1, \cdots, q_r\}$ orthogonal vectors that span $\{a_1, \cdots, a_r\}$. That is span($\{a_1, \cdots, a_r\}$) = span($\{q_1, \cdots, q_r\}$)

**Proof:**

By induction. Base case $r = 1$, $q_1 = \frac{1}{R_1}a_1$, $R_{11} = ||a_1||_2$

Case $r = 2$, $R_{12} = {q_1^\prime}a_2$

$\tilde{q}_2 = a_2 - R_{12}q_1$, $R_{22} = ||\tilde{q}_2||_2$, $q_2 = \frac{1}{R_{22}}\tilde{q}_1$

Induction, suppose $i \leq r - 1$, What we want to show: 

(1) $q_1, \cdots, q_r$ span $a_1, \cdots, a_r$

(2) $q_r^\prime q_i = 0$, $i \leq r - 1$

(3) $q_r^\prime q_r = 1$

Def: 

$$\begin{align}
R_{ir} &= q_i^\prime a_r \\
\tilde{q}_r &= a_r - \sum_{i = 1}^{r-1}R_{ir}q_i \\
R_{rr} &= ||\tilde{q}_r||_2 \\
q_r &= \frac{1}{R_{rr}}\tilde{q}_r
\end{align}$$

Further,

$$\begin{align}
q_r^\prime q_i &= q_r^\prime a_r - \sum_{j = 1}^{r-1}R_{jr}q_j^\prime q_i \\
& = q_r^\prime a_r -R_{ir} \\
& = 0
\end{align}$$

Then,
$$\begin{align}
\sum_{i = 1}^{r}R_{ir}q_i &= \sum_{i = 1}^{r-1}R_{ir}q_i + R_{rr}q_r \\
&= \sum_{i = 1}^{r-1}R_{ir}q_i + R_{rr}\frac{1}{R_{rr}}\tilde{q}_r \\
&= \sum_{i = 1}^{r-1}R_{ir}q_i + R_{rr}\frac{1}{R_{rr}} (a_r - \sum_{i = 1}^{r-1}R_{ir}q_i)\\
&= a_r
\end{align}$$

Thus,
$$\begin{equation}
\begin{bmatrix}a_1 & a_2 & \cdots & a_r \end{bmatrix} = \begin{bmatrix}q_1 & q_2 & \cdots & q_r \end{bmatrix}
\begin{bmatrix}
  R_{1,1} & R_{1,2} & \cdots & R_{1,r} \\
  0 & R_{2,2} & \cdots & R_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  0 & 0 & \cdots & R_{r,r} 
 \end{bmatrix}
 \end{equation}$$


### Theorem: QR decompostion
Let $A \in R^{n \times m}$. There exists:

**(a)** $Q\in R^{n\times n}$, orthogonal matrix. **(b)**$R \in R^{r\times r}$, upper triangular matrix. 

**(c)**$S \in R^{r \times (m-r)}$. **(d)** $\pi \in R^{m \times m}$, permutation matrix.

$$\begin{equation} A = Q \begin{bmatrix}R & S\\ 0 & 0 \end{bmatrix} \pi^\prime\end{equation}$$

**proof:**

We can always find a permutation matrix $\pi$ such that the first $r$ column of $A\pi$ are linearly independent. 
This is because rank($A$) = $r$ and $A$ has $r$ linearly independent columns. By using Gram-Schmidt Process, $\exists \tilde{Q} \in R^{n \times r} \,\,\&\,\, R \in R^{r \times r}$, $s.t$

$$\begin{equation} \begin{bmatrix}a_1 & a_2 & \cdots & a_r \end{bmatrix} = \tilde{Q}R \end{equation}$$

For $j = r+1, \cdots, m$, $\exists S_{k(j - r)}$, $k = 1, \cdots, r$, $s.t$
$$a_j = \sum_{k = 1}^{r}S_{k(j - r)}a_k$$

Thus,
$$A\pi = \tilde{Q} \begin{bmatrix}R & S\end{bmatrix}$$

Further, after completing $\tilde{Q}$ we get,
$$A\pi = Q \begin{bmatrix}R & S \\ 0 & 0\end{bmatrix}$$


**HW problem 1: Complete Q** 

**HW problem 2: Implement regular gram-schmidt assuming A has full column rank.**

Examples that show function works well enough

**HW problem 3: Examples that show that gram-schmidt fails to recover**

**HW problem 4: Look up Modified Gram-Schmidt, Implement it.**

**HW problem 5(Optional Pivoting):** Implement MGS with column pivoting. Find an example where mgs fail while the mgs with column pivoting does not.

Two useful paper: 

1. Businger, Galub: Linear Least Squares by Householder transformation

2. Engler, The behavior of QR factorization algorithm with col pivoting

**My answer for problem 2 and 4, Implementation**

**reference:** 

http://www4.ncsu.edu/eos/users/w/white/www/white/ma580/chap3.3.PDF

https://www.math.ucla.edu/~yanovsky/Teaching/Math151B/handouts/GramSchmidt.pdf

In [2]:
using LinearAlgebra

## Gram-Schmidt QR decompostion
## With only one loop

function gramschmidtQR(A)
    """
    Implement the gram-schmidt procedure. 
    Input a full column rank matrix A.
    Output Q and R.
    """
    m, n = size(A)
    r = rank(A)
    if r != n
        println("The input matrix is not full column rank")
    else
        u1 = A[:,1]
        e1 = u1 ./ norm(u1)
        e = e1
        R = zeros(n,1)
        R[1] = A[:,1]'e1
        for i in 2:n
            ui = A[:, i] - sum(e.* (A[:,i]'*e), dims = 2)
            e = hcat(e, ui ./ norm(ui))
            t = zeros(n,1)
            t[1:i] = A[:,i]'*e
            R = hcat(R, t)
        end
    end
    return e, R
end
    
A = [1 1 0; 1 0 1; 0 1 1]
Q, R = gramschmidtQR(A)


([0.707107 0.408248 -0.57735; 0.707107 -0.408248 0.57735; 0.0 0.816497 0.57735], [1.41421 0.707107 0.707107; 0.0 1.22474 0.408248; 0.0 0.0 1.1547])

In [3]:
Q 

3×3 Array{Float64,2}:
 0.707107   0.408248  -0.57735
 0.707107  -0.408248   0.57735
 0.0        0.816497   0.57735

In [4]:
R

3×3 Array{Float64,2}:
 1.41421  0.707107  0.707107
 0.0      1.22474   0.408248
 0.0      0.0       1.1547  

In [8]:
## Gram-Schmidt QR decompostion
## With two loops
function gramschmidtQR2(A)
    """
    Implement the gram-schmidt procedure. 
    Input a full column rank matrix A.
    Output Q and R.
    """
    m, n = size(A)
    r = rank(A)
    if r != n
        println("The input matrix is not full column rank")
    else
        Q = zeros(m, n)
        R = zeros(n,n)
        R[1,1] = norm(A[:,1])
        Q[:,1] = A[:,1]./R[1,1]
        for k = 2:n
            z = A[:, k]
            for i = 1:k-1
                R[i,k] = A[:,k]'Q[:,i]
                z = z - R[i,k]Q[:,i]
            end
            R[k,k] = norm(z)
            Q[:, k] = z ./ R[k,k]
        end
    end
    return Q, R
end
    
A = [1 1 0; 1 0 1; 0 1 1]
Q, R = gramschmidtQR2(A)


([0.707107 0.408248 -0.57735; 0.707107 -0.408248 0.57735; 0.0 0.816497 0.57735], [1.41421 0.707107 0.707107; 0.0 1.22474 0.408248; 0.0 0.0 1.1547])

In [9]:
Q

3×3 Array{Float64,2}:
 0.707107   0.408248  -0.57735
 0.707107  -0.408248   0.57735
 0.0        0.816497   0.57735

In [10]:
R

3×3 Array{Float64,2}:
 1.41421  0.707107  0.707107
 0.0      1.22474   0.408248
 0.0      0.0       1.1547  

In [5]:
## Modified gram-schmidt QR decompostion
## With two loops

function modifiedGSQR(A)
    """
    Implement the modifies gram-schmidt procedure.
    Input a full column rank matrix A.
    Output Q and R.
    """
    m, n = size(A)
    r = rank(A)
    if r != n
        println("The input matrix is not full column rank")
    else
        Q = float(A)
        R = zeros(n,n)
        for k = 1:n
            R[k,k] = norm(Q[:,k])
            Q[:,k] = Q[:,k] ./ R[k,k]
            for j = k+1:n
                R[k,j] = A[:,j]'Q[:,k]
                Q[:,j] = Q[:,j] - R[k,j]Q[:,k]
            end
        end
    end
    return Q, R
end

A = [1 1 1; 1 1 0 ; 1 0 2;1 0 0]
Q, R = modifiedGSQR(A)

([0.5 0.5 0.316228; 0.5 0.5 -0.316228; 0.5 -0.5 0.632456; 0.5 -0.5 -0.632456], [2.0 1.0 1.5; 0.0 1.0 -0.5; 0.0 0.0 1.58114])

In [6]:
Q

4×3 Array{Float64,2}:
 0.5   0.5   0.316228
 0.5   0.5  -0.316228
 0.5  -0.5   0.632456
 0.5  -0.5  -0.632456

In [7]:
R

3×3 Array{Float64,2}:
 2.0  1.0   1.5    
 0.0  1.0  -0.5    
 0.0  0.0   1.58114

### Algorithms for QR factoriztion

**Gram-Schmidt algorithm** : not recommended in practice(sensitive to rounding errors)

**Modified Gram-Schmidt algorithm** : Better numerical properties

**Householder algorithm**: represents Q as a product of elementary orthogonal matrices. the most widely used algorithm

### Householder Refelctions

reference: 
https://www.keithlantz.net/2012/05/qr-decomposition-using-householder-transformations/

A Householder reflections is $H = I - 2vv^T$, where $||v||_2 = 1$

$Hx$ is the refelction of $x$ about the hyperplane passing through the origin with normal vector $v$.

**HW problem 6 Lemma** Householder reflections are orthogonal matrix.

$H^T = (I - 2vv^T)^T = H$, $H$ is symmetric matrix

$H^TH = (I - 2vv^T)(I - 2vv^T) = I - 4vv^T + 4vv^Tvv^T = I - 4vv^T + 4vv^T = I$

$Hv = (I - 2vv^T)v = -v$

For a vector u orthogonal to v, we have

$Hu = (I - 2vv^T)u = u$

### Givens Rotations

A Given rotation $G^{(i,j)}$ where $G^{(i,j)}$ is 
1. The $i^{th}$, $j^{th}$ elements on diag take $\lambda$
2. All the other diagonal elements are 1
3. $G_{i,j}^{(i,j)} = \sigma$
4. $G_{j,i}^{(i,j)} = -\sigma$

Example $G^{(2,4)} = \begin{bmatrix}1 & 0 &0&0 \\ 
0 & \lambda &0&\sigma \\
0 & 0 & 1 & 0 \\
0 & -\sigma & 0 & \lambda \end{bmatrix}$

**HW problem 7:** Show that a Givens Rotation is orthogonal when $\lambda^2 + \sigma^2 = 1$

**My answer:**

${G^{(i,j)}}^TG^{(i,j)} = H$, where $H$ satisfies:
1. The ith and jth elements on diag take $\lambda^2 + \sigma^2$.
2. The other elements on diag take $1$.
3. The other elements is zero.

Thus, $G^{(i,j)}$ is orthogonal $\iff$ $\lambda^2 + \sigma^2 = 1$
